interface ZIF_C_EP028_VACANCY_HEAD_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZC_EP028_VACANCY_HEAD,
 CREATE_ZC_EP028_VACANCY_HEAD   TYPE /BOBF/ACT_KEY VALUE '97B39E788CD71EDE8C8CCAA62574B9DF',
 DELETE_ZC_EP028_VACANCY_HEAD   TYPE /BOBF/ACT_KEY VALUE '97B39E788CD71EDE8C8CCAA6257539DF',
 LOCK_ZC_EP028_VACANCY_HEAD     TYPE /BOBF/ACT_KEY VALUE '97B39E788CD71EDE8C8CCAA62573F9DF',
 SAVE_ZC_EP028_VACANCY_HEAD     TYPE /BOBF/ACT_KEY VALUE '97B39E788CD71EDE8C8CCAA62575B9DF',
 UNLOCK_ZC_EP028_VACANCY_HEAD   TYPE /BOBF/ACT_KEY VALUE '97B39E788CD71EDE8C8CCAA6257439DF',
 UPDATE_ZC_EP028_VACANCY_HEAD   TYPE /BOBF/ACT_KEY VALUE '97B39E788CD71EDE8C8CCAA62574F9DF',
 VALIDATE_ZC_EP028_VACANCY_HEAD TYPE /BOBF/ACT_KEY VALUE '97B39E788CD71EDE8C8CCAA6257579DF',
      END OF ZC_EP028_VACANCY_HEAD,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZC_EP028_VACANCY_HEAD,
        BEGIN OF LOCK_ZC_EP028_VACANCY_HEAD,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZC_EP028_VACANCY_HEAD,
        BEGIN OF UNLOCK_ZC_EP028_VACANCY_HEAD,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZC_EP028_VACANCY_HEAD,
      END OF ZC_EP028_VACANCY_HEAD,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZC_EP028_VACANCY_HEAD,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '97B39E788CD71EDE8C8CCAA62573D9DF',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '97B39E788CD71EDE8C8CCAA6257399DF',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '97B39E788CD71EDE8C8CCAA6257499DF',
      END OF ZC_EP028_VACANCY_HEAD,
      BEGIN OF ZC_EP028_VACANCY_HEAD_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '97B39E788CD71EDE8C8CCAA6257619DF',
      END OF ZC_EP028_VACANCY_HEAD_LOCK,
      BEGIN OF ZC_EP028_VACANCY_HEAD_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '97B39E788CD71EDE8C8CCAA62575F9DF',
      END OF ZC_EP028_VACANCY_HEAD_MESSAGE,
      BEGIN OF ZC_EP028_VACANCY_HEAD_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '97B39E788CD71EDE8C8CCAA6257639DF',
      END OF ZC_EP028_VACANCY_HEAD_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZC_EP028_VACANCY_HEAD,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZC_EP028_VACANCY_HEAD,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '97B39E788CD71EDE8C8CCAA62572F9DF' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZC_EP028_VACANCY_HEAD' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZC_EP028_VACANCY_HEAD,
 CREATE_BY_JPRF                 TYPE /BOBF/DET_KEY VALUE '97B39E788CD71EDE8CA63E7FE76239DF',
      END OF ZC_EP028_VACANCY_HEAD,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZC_EP028_VACANCY_HEAD          TYPE /BOBF/OBM_GROUP_KEY VALUE '97B39E788CD71EDE8CA733D8138579DF',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZC_EP028_VACANCY_HEAD          TYPE /BOBF/OBM_NODE_KEY VALUE '97B39E788CD71EDE8C8CCAA6257339DF',
 ZC_EP028_VACANCY_HEAD_LOCK     TYPE /BOBF/OBM_NODE_KEY VALUE '97B39E788CD71EDE8C8CCAA62573B9DF',
 ZC_EP028_VACANCY_HEAD_MESSAGE  TYPE /BOBF/OBM_NODE_KEY VALUE '97B39E788CD71EDE8C8CCAA6257379DF',
 ZC_EP028_VACANCY_HEAD_PROPERTY TYPE /BOBF/OBM_NODE_KEY VALUE '97B39E788CD71EDE8C8CCAA6257479DF',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZC_EP028_VACANCY_HEAD,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  JPRF_ID                        TYPE STRING VALUE 'JPRF_ID',
  POS_ID                         TYPE STRING VALUE 'POS_ID',
  JOB_ID                         TYPE STRING VALUE 'JOB_ID',
  VACANCY_DESCR                  TYPE STRING VALUE 'VACANCY_DESCR',
  DEPARTMENT                     TYPE STRING VALUE 'DEPARTMENT',
  DEPARTMENT_NAME                TYPE STRING VALUE 'DEPARTMENT_NAME',
  DIRECTORATE                    TYPE STRING VALUE 'DIRECTORATE',
  DIRECTORATE_NAME               TYPE STRING VALUE 'DIRECTORATE_NAME',
  LINK_JOB_DESCR                 TYPE STRING VALUE 'LINK_JOB_DESCR',
  LOCATION                       TYPE STRING VALUE 'LOCATION',
  SUBAREA                        TYPE STRING VALUE 'SUBAREA',
  WORK_SCHED                     TYPE STRING VALUE 'WORK_SCHED',
  GRADE                          TYPE STRING VALUE 'GRADE',
  GRAD2                          TYPE STRING VALUE 'GRAD2',
  COMP_SLOT                      TYPE STRING VALUE 'COMP_SLOT',
  VACANCY_TYPE                   TYPE STRING VALUE 'VACANCY_TYPE',
  HR_REPR                        TYPE STRING VALUE 'HR_REPR',
  STATUS                         TYPE STRING VALUE 'STATUS',
  COMMENTS                       TYPE STRING VALUE 'COMMENTS',
  UPDATE_DATE_TIME               TYPE STRING VALUE 'UPDATE_DATE_TIME',
  UPDATE_USER                    TYPE STRING VALUE 'UPDATE_USER',
      END OF ZC_EP028_VACANCY_HEAD,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZC_EP028_VACANCY_HEAD,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '97B39E788CD71EDE8C8CCAA6257359DF',
      END OF ZC_EP028_VACANCY_HEAD,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZC_EP028_VACANCY_HEAD,
 CAN_DELETE                     TYPE /BOBF/VAL_KEY VALUE '97B39E788CD71EDE8CB4FE903FF339DF',
 CREATE_BY_JPRF                 TYPE /BOBF/VAL_KEY VALUE '97B39E788CD71EDE8CA733D8138519DF',
 STRUCTURE_CHECK                TYPE /BOBF/VAL_KEY VALUE '97B39E788CD71EDE8D990B3E7FC619DF',
      END OF ZC_EP028_VACANCY_HEAD,
    END OF SC_VALIDATION .
endinterface.
