interface ZIF_EP028_BOPF_VACANCY_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ROOT,
 CREATE_BY_JPRF                 TYPE /BOBF/ACT_KEY VALUE '7F4B49222FC81EDD8AECA4896BA5FEE3',
 CREATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0319F87',
 DELETE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0321F87',
 LOCK_ROOT                      TYPE /BOBF/ACT_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B030DF87',
 SAVE_ROOT                      TYPE /BOBF/ACT_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0329F87',
 UNLOCK_ROOT                    TYPE /BOBF/ACT_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0311F87',
 UPDATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B031DF87',
 VALIDATE_ROOT                  TYPE /BOBF/ACT_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0325F87',
      END OF ROOT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ROOT,
        BEGIN OF CREATE_BY_JPRF,
 JPRF_ID                        TYPE STRING VALUE 'JPRF_ID',
        END OF CREATE_BY_JPRF,
        BEGIN OF LOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ROOT,
        BEGIN OF UNLOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ROOT,
      END OF ROOT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ROOT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B030BF87',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0307F87',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0317F87',
      END OF ROOT,
      BEGIN OF ROOT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B032FF87',
      END OF ROOT_LOCK,
      BEGIN OF ROOT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B032DF87',
      END OF ROOT_MESSAGE,
      BEGIN OF ROOT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0331F87',
      END OF ROOT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ROOT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '7F4B49222FC81EDD8AE7D76A6615DED9' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZBOPF_EP028_VACANCY' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ROOT                           TYPE /BOBF/OBM_NODE_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0301F87',
 ROOT_LOCK                      TYPE /BOBF/OBM_NODE_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0309F87',
 ROOT_MESSAGE                   TYPE /BOBF/OBM_NODE_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0305F87',
 ROOT_PROPERTY                  TYPE /BOBF/OBM_NODE_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0315F87',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ROOT,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  JPRF_ID                        TYPE STRING VALUE 'JPRF_ID',
  POS_ID                         TYPE STRING VALUE 'POS_ID',
  VACANCY_DESCR                  TYPE STRING VALUE 'VACANCY_DESCR',
  DEPARTMENT                     TYPE STRING VALUE 'DEPARTMENT',
  DEPARTMENT_NAME                TYPE STRING VALUE 'DEPARTMENT_NAME',
  DIRECTORATE                    TYPE STRING VALUE 'DIRECTORATE',
  DIRECTORATE_NAME               TYPE STRING VALUE 'DIRECTORATE_NAME',
  LINK_JOB_DESCR                 TYPE STRING VALUE 'LINK_JOB_DESCR',
  LOCATION                       TYPE STRING VALUE 'LOCATION',
  WORK_SCHED                     TYPE STRING VALUE 'WORK_SCHED',
  GRADE                          TYPE STRING VALUE 'GRADE',
  COMP_SLOT                      TYPE STRING VALUE 'COMP_SLOT',
  VACANCY_TYPE                   TYPE STRING VALUE 'VACANCY_TYPE',
  HR_REPR                        TYPE STRING VALUE 'HR_REPR',
  STATUS                         TYPE STRING VALUE 'STATUS',
  COMMENTS                       TYPE STRING VALUE 'COMMENTS',
  TRANSIENT_NODE_DATA            TYPE STRING VALUE 'TRANSIENT_NODE_DATA',
  DUMMY                          TYPE STRING VALUE 'DUMMY',
      END OF ROOT,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ROOT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0303F87',
      END OF ROOT,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_QUERY,
      BEGIN OF ROOT,
 SELECT_ALL                     TYPE /BOBF/OBM_QUERY_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0333F87',
 SELECT_BY_ELEMENTS             TYPE /BOBF/OBM_QUERY_KEY VALUE '7F4B49222FC81EDD8AE7E6C9B0335F87',
      END OF ROOT,
    END OF SC_QUERY .
  constants:
    BEGIN OF SC_QUERY_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF SELECT_BY_ELEMENTS,
 KEY                            TYPE STRING VALUE 'KEY',
 PARENT_KEY                     TYPE STRING VALUE 'PARENT_KEY',
 ROOT_KEY                       TYPE STRING VALUE 'ROOT_KEY',
 NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
 JPRF_ID                        TYPE STRING VALUE 'JPRF_ID',
 POS_ID                         TYPE STRING VALUE 'POS_ID',
 VACANCY_DESCR                  TYPE STRING VALUE 'VACANCY_DESCR',
 DEPARTMENT                     TYPE STRING VALUE 'DEPARTMENT',
 DEPARTMENT_NAME                TYPE STRING VALUE 'DEPARTMENT_NAME',
 DIRECTORATE                    TYPE STRING VALUE 'DIRECTORATE',
 DIRECTORATE_NAME               TYPE STRING VALUE 'DIRECTORATE_NAME',
 LINK_JOB_DESCR                 TYPE STRING VALUE 'LINK_JOB_DESCR',
 LOCATION                       TYPE STRING VALUE 'LOCATION',
 WORK_SCHED                     TYPE STRING VALUE 'WORK_SCHED',
 GRADE                          TYPE STRING VALUE 'GRADE',
 COMP_SLOT                      TYPE STRING VALUE 'COMP_SLOT',
 VACANCY_TYPE                   TYPE STRING VALUE 'VACANCY_TYPE',
 HR_REPR                        TYPE STRING VALUE 'HR_REPR',
 STATUS                         TYPE STRING VALUE 'STATUS',
 COMMENTS                       TYPE STRING VALUE 'COMMENTS',
 TRANSIENT_NODE_DATA            TYPE STRING VALUE 'TRANSIENT_NODE_DATA',
 DUMMY                          TYPE STRING VALUE 'DUMMY',
        END OF SELECT_BY_ELEMENTS,
      END OF ROOT,
    END OF SC_QUERY_ATTRIBUTE .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ROOT,
 CAN_CREATE                     TYPE /BOBF/VAL_KEY VALUE '7F4B49222FC81EDD8B83C15AA77CF277',
      END OF ROOT,
    END OF SC_VALIDATION .
endinterface.
